title: Вода в вашем доме
url: "https://voda53.cloudvent.net"
phone: +79216958007
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Водоснабжение, водоотведение, дренаж для частных жилых домов, дач и бань в Великом Новгороде и Новгородской области

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  phone: +79216958007
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Вода в вашем доме
  links:
    - https://vk.com/id466853316

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  uslugi:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "uslugi"
    values:
      layout: "usluga"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  - Vkontakte
